"""Teams Table tema_id fix

Revision ID: 32d1ccfe8122
Revises: 08ce263bedb0
Create Date: 2024-04-13 19:23:04.060024

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "32d1ccfe8122"
down_revision = "08ce263bedb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
