"""Teams Table team_id

Revision ID: 3bcacd670e1e
Revises: 32d1ccfe8122
Create Date: 2024-04-13 21:07:37.060321

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bcacd670e1e"
down_revision = "32d1ccfe8122"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll", sa.Column("team_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll", "team_id")
    # ### end Alembic commands ###
