"""Teams Table tema_id

Revision ID: dce2a9468f9d
Revises: 7d85b496a611
Create Date: 2024-04-13 18:55:08.269397

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "dce2a9468f9d"
down_revision = "7d85b496a611"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("id_team", sa.Integer(), nullable=False))
    op.add_column(
        "teams",
        sa.Column("name_team", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("teams", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("teams", "name_team")
    op.drop_column("teams", "id_team")
    # ### end Alembic commands ###
